# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99909d6b25ef6b6583de680565bb91537340057b33cc6599d5544a2a51d3f48c33ed11bfa182b950e0249f9bc202d45aa8bf7e199b09586d124ab2927d36a1b8

test:
  secret_key_base: c421581be1fa83c78489bdce98c04f6c05ebc576db23bb78952fa45f2cc4bc8187efc39cd67d1bccd720c3db277ac3b3824f72950f29fb321e88157fce07f90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
